# Generated by Django 4.2 on 2023-06-26 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0004_categories_alter_product_options_sizes_colors_assets_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="seller",
        ),
    ]
